### ISSUE TITLE
UI: Remove "Pending Review" button.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#28]
When editing a `future` revision, the pending review button shows up. 

It should not show up since it's irrelevant and doesn't work.

## Challenges
The pending review button does not have any obvious characteristics that we can hook into to remove/hide it via JS or CSS.

## Notes:

It displays if:
 - It has an `wp:action-publish`, which comes from the Rest api.
 - It is not in `publish` or  `private` or `( post.status === 'future' && ! isInTheFuture ) )` - _simplified_
 
**Reference**
https://github.com/WordPress/gutenberg/blob/f622315c8fd962f8e02a06c5e2d800049ec0b93a/packages/editor/src/components/post-pending-status/check.js#L17

## Interface
| UI | HTML |
| --- | ---|
![](https://d.pr/i/SSjFvp.png) | ![](https://d.pr/i/jVURdZ.png)

**Comment by iandunn** [comment]
This won't help in the short term, but I'd be tempted to file an upstream bug. I'm guessing the obfuscation is an unintended consequence of introducing CSS Modules or something. Gutenberg shouldn't be intentionally making it harder for people to customize their sites.

**Comment by ryelle** [comment]
The awkward class name is from the CSS-in-JS library on the checkbox control, but they do pass through the className (that's why it has `components-*`).

It looks like some of the other `PanelRow`s have classes, I would open an issue or PR to [add a class here](https://github.com/WordPress/gutenberg/blob/2b55fced9aba19e6d63e708a2570eeeb730e870a/packages/edit-post/src/components/sidebar/post-pending-status/index.js#L13), like exists on [the visibility `PanelRow`](https://github.com/WordPress/gutenberg/blob/2b55fced9aba19e6d63e708a2570eeeb730e870a/packages/edit-post/src/components/sidebar/post-visibility/index.js#L16). This is the level you'd want to hide anyway, having an empty panel-row would probably add extra space.

Or, if you need even more customization, you can disable this whole panel with this (see https://github.com/WordPress/gutenberg/issues/17407):

```
wp.data.dispatch( 'core/edit-post' ).removeEditorPanel( 'post-status' );
```

and register your own with the [`PluginDocumentSettingPanel` slotfill](https://developer.wordpress.org/block-editor/packages/packages-edit-post/#PluginDocumentSettingPanel).
