### ISSUE TITLE
Revisions for trashed posts hang around

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#37]
I think we discussed this in passing and I can't remember the outcome, but if you create a revision and then trash the page the revision still exists.

Should we delete the revision?

**Comment by coreymckrill** [comment]
When a post is permanently deleted, the revisions do get deleted also, but that doesn't happen when a post is just trashed.

I've been contemplating that maybe we should either enable the `trash` status for revisions as well, or create a new `inactive` status. The `inactive` one would cover more scenarios, because it could also be used if a post is unpublished to `draft` or `pending`. Then I guess the question would be, if a post is republished, or untrashed, would the revisions be reactivated automatically? I think I would lean towards "no".

**Comment by StevenDufresne** [comment]
Right. The challenge is that page/posts are so easily trashed and recovered, which is most likely by design...

>Then I guess the question would be, if a post is republished, or untrashed, would the revisions be reactivated automatically? I think I would lean towards "no".

I think you would turn them back on but remove the scheduled date?
