### ISSUE TITLE
Viewing revision on /revision.php is not working.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#5]
It appears as the problem lies here:
https://github.com/WordPress/wordpress-develop/blob/b44dd453ed4463a7f29e7c890d228e7ca40986ef/src/wp-admin/includes/revision.php#L322

Quick debugging reveals: 
`$from = 0`,  which leaves the ui to compare `0:{revision-id}`

That creates some Javascript errors in the console.

**Comment by coreymckrill** [comment]
With #43 we have a functional revision comparison screen. The URL is almost the same as the normal revision screen, with one extra query parameter: `/wp-admin/revision.php?page=compare-updates&revision_id={$revision_id}`. The other query parameters that can be used by the default revision screen, `to` and `from`, are not used on this one.

@StevenDufresne I'm leaving this open for now so that any links to compare revisions in the block editor can be updated. If you'd rather address those in a separate issue, feel free to close this.
