### ISSUE TITLE
Update Revision Publish API endpoint

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#6]
We are currently using a custom REST endpoint to `publish` the revision. 

The endpoint URL should look like: ...`/34/posts/344/publish` or `/34/pages/344/publish`.

The problem is that the consumer interacting with this endpoint is typically out of context, meaning they don't know the original post type. The consumer can obtain that information but would have to make another call using the `parent` property to grab the original post/page which makes the UI needlessly complicated.

**Suggestions**:
- Append `parentType` to the revision on creation _or_
- The backend fetches the parent type, removing the need for it in the URL. 

Alternatively, since we seem to be moving forward with modifying the internal revision type and getting the Block Editor to work, we could solve this by not having a separate REST endpoint for publishing and use the existing publish method (not sure what that would entail).

**Comment by coreymckrill** [comment]
`publish` might not be the right word for that endpoint, since what we're really doing is updating a _post_ with the contents of a _revision_. Regardless, I think we need to keep that endpoint separate. The normal way of publishing a post via REST would be via the `update` endpoint, changing the post status, but that won't work in this case because updating the contents of a revision is a very different procedure than updating a post with a revision.

I do think we can modify the endpoint path and remove the need for a parent type and ID. We could make it just `/revision/123/publish`
