### ISSUE TITLE
Sidebar confusion

### ISSUE THREAD

**Issue by bph** [WordPress/revisions-extended#67]
To orient myself, I need landmarks... 
<img width="323" alt="Screen Shot 2021-02-20 at 9 23 52 AM" src="https://user-images.githubusercontent.com/39980/108598763-837b9800-735d-11eb-8f0f-446f50e698c4.png">

Can the word 'Revision' be replaced with "Scheduled Update"? Revision is already used in my brain for something else.  

I am unsure, what to do with **Publish immediately**, but I am willing to try it :-) as what's the worst that can happen that i overwrite the existing with a half finished update. 

The **Delete permanently** however scares me. Am I deleting just this scheduled update or the whole page?

**Comment by StevenDufresne** [comment]
> Can the word 'Revision' be replaced with "Scheduled Update"? Revision is already used in my brain for something else.

Although I don't want to reach too much into the future, the next milestone should contain updates that are not `scheduled`. So I'm not sure we want it to say "Scheduled" but I agree, it should at least say _Update_. 

> I am unsure, what to do with **Publish immediately**, but I am willing to try it :-) as what's the worst that can happen that i overwrite the existing with a half finished update.

Not sure what this statement is suggesting 😜. 

> The **Delete permanently** however scares me. Am I deleting just this scheduled update or the whole page?

That's fair, it is strong language. I think if we get the landmarks right, it should make sense and since deleting a revision is irreversible, the strong language is somewhat warranted. Additionally, if you click on that button you still get a confirmation window to make sure you don't lose everything.

**Comment by coreymckrill** [comment]
+1 for **Update**, since there will also potentially be "pending" updates at some point.

**Delete permanently** is the same language used elsewhere in the WP Admin to indicate that something will be removed from the database, rather than just switched to a "trash" status. Updates don't currently support being "trashed" so we want to make it very clear that you can't undo it if you delete it. I'm not really sure how to indicate that this is only the update that is getting deleted, not the parent post.

**Comment by bph** [comment]
"Update" works for me. 

The **Delete permanently** is a bit scary as long as the user is till unsure what they are exactly working on. Is it the update or is it the original page? 

I am aware that this is the same language as everywhere else. Until now, it's clearly defined. This page and post. 
_Not a variation_ of that page or post. 

If the confirmation screen could indicate that **delete permanently** only concerns the Update and not the original page the user should be fine. It's not as easily decipherable when everything else is a bit ambiguous.  I am over dramatizing it. It's probably fine for less timid people...

**Comment by bph** [comment]
>I am unsure, what to do with Publish immediately, but I am willing to try it :-) as what's the worst that can happen that i overwrite the existing with a half finished update.
>>Not sure what this statement is suggesting 😜. 

@StevenDufresne I was just trying to convey my confusion, when first working on this, that if everything looks the same like the original page, I might confuse the two, which doesn't have consequences when publishing, but it might be more grave when deleting something permanently.  Anyway..
