### ISSUE TITLE
Edits to original page can be unintentionally overwritten

### ISSUE THREAD

**Issue by iandunn** [WordPress/revisions-extended#73]
1. User A schedules a revision to a page
2. User B doesn't realize that, and updates the original page
3. The revision is automatically published, overwriting User B's edits

A simple mitigation might be to display a warning at the top of the page, like `This page has a scheduled revision. Any changes you make to this will be overwritten.`

A more aggressive-but-reliable solution would be to disable the `Update` button on the original, so that User B has to update User A's revision rather than the original.

**Comment by coreymckrill** [comment]
One tiny step we've done to address this is add a post state to the list table that says "Has Update" for all posts that have one. I agree that we should also indicate it in the editor, somewhere.

> A more aggressive-but-reliable solution would be to disable the Update button on the original, so that User B has to update User A's revision rather than the original.

That's a really interesting idea. Maybe it would almost be like having the post "locked" because another user is editing it. "This post has a scheduled update, so it cannot be edited. Edit the update instead." And then of course you could publish the update immediately if you decided the changes couldn't wait.

That might be too aggressive though. A middle ground might be a popup warning if you try to save changes to a post that already has an update.

**Comment by coreymckrill** [comment]
🤔 We could also "pin" an update to the latest revision of a post, so if the post later gets changed and has a new latest revision, the update would become "obsolete".

**Comment by StevenDufresne** [comment]
Locking the post may not be an option. I can envision a scenario where updates are queued for 2 months in the future to coincide with an event but the current document has information that needs immediate change.

Without building a rebase/diff tool, I think the best we can do (as Ian pointed out) is to add a confirmation that explains that it will be overwritten on _X date_ and/or gives them the option to delete the revision?

**Comment by coreymckrill** [comment]
"Add a confirmation that explains that it will be overwritten on X date and gives them the option to edit or delete the revision"

Modified slightly from above, I think this is the best solution for now.
