### ISSUE TITLE
Add documentation to the UI

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/revisions-extended#84]
- [ ] On the list table screen, we can use use WP Admin's existing Help Tab functionality to add some documentation
- [ ] ~In the block editor, maybe we'd want to add a dismissable modal like the one introducing the editor to new users?~

**Comment by iandunn** [comment]
>  On the list table screen, we can use use WP Admin's existing Help Tab functionality to add some documentation

It may be helpful to have a link drawing people's attention to it, since IMO most people don't realize the `Help` tab exists, or don't think to look at it when they need help. 

https://github.com/WordPress/wordcamp.org/blob/07d78e46d5593c5692ed190c48c5081d30d3e773/public_html/wp-content/plugins/wordcamp-remote-css/views/page-remote-css.php#L50

**Comment by coreymckrill** [comment]
Crossed out the item for a modal in the block editor. With #94, let's see how well our "self-documenting" UI works, and then re-assess.
